import type { RouteNode, WagonBlueprint } from '../simulation/core/types'

export const wagonBlueprints: WagonBlueprint[] = [
  {
    id: 'wagon-mimi',
    name: 'Oficina dos Trilhos',
    leaderId: 'mimi',
    description: 'Libera o primeiro vagao de engenharia permanente para reforco e reparo.',
    costBlueprints: 1,
    costMemories: 1,
    upgradeName: 'Guindaste Blindado',
    upgradeDescription: 'Defesas comecam no nivel 1 e o trem ganha mais integridade de casca.',
    upgradeCostBlueprints: 2,
    upgradeCostMemories: 2,
  },
  {
    id: 'wagon-tico',
    name: 'Carro-Lanterna',
    leaderId: 'tico',
    description: 'Adiciona um modulo de luz que estabiliza a linha do trem e o humor da tripulacao.',
    costBlueprints: 1,
    costMemories: 2,
    upgradeName: 'Farol de Vigilia',
    upgradeDescription: 'Postes de luz comecam ativos e o estoque de oleo cresce antes da partida.',
    upgradeCostBlueprints: 2,
    upgradeCostMemories: 2,
  },
  {
    id: 'wagon-nina',
    name: 'Atelie de Retalhos',
    leaderId: 'nina',
    description: 'Cria um espaco de remendo e abrigo para novos recrutas.',
    costBlueprints: 2,
    costMemories: 2,
    upgradeName: 'Refugio Costurado',
    upgradeDescription: 'Suportes comecam prontos e a tripulacao leva tecido extra para improviso.',
    upgradeCostBlueprints: 2,
    upgradeCostMemories: 3,
  },
  {
    id: 'wagon-bento',
    name: 'Cozinha de Trem',
    leaderId: 'bento',
    description: 'Aumenta a sensacao de casa entre runs e prepara racoes para a proxima parada.',
    costBlueprints: 2,
    costMemories: 2,
    upgradeName: 'Caldeirao de Vigilia',
    upgradeDescription: 'Comida extra no inicio e eventos positivos passam a render refeicoes adicionais.',
    upgradeCostBlueprints: 2,
    upgradeCostMemories: 3,
  },
  {
    id: 'wagon-lua',
    name: 'Observatorio',
    leaderId: 'lua',
    description: 'Abre leitura melhor das rotas e dos eventos da proxima estacao.',
    costBlueprints: 2,
    costMemories: 3,
    upgradeName: 'Carta de Campo',
    upgradeDescription: 'Caches extras surgem na estacao e alongam runs com mais seguranca.',
    upgradeCostBlueprints: 3,
    upgradeCostMemories: 3,
  },
  {
    id: 'wagon-sombra',
    name: 'Carro da Memoria',
    leaderId: 'sombra',
    description: 'Amplia o espaco de ecos e pistas deixadas entre estacoes.',
    costBlueprints: 3,
    costMemories: 3,
    upgradeName: 'Eco Profundo',
    upgradeDescription: 'Eventos misteriosos rendem memoria extra e deixam a run mais rica em pistas.',
    upgradeCostBlueprints: 3,
    upgradeCostMemories: 4,
  },
]

export function createInitialRouteNodes(): RouteNode[] {
  return [
    {
      id: 'quiet-platform',
      name: 'Plataforma Silenciosa',
      biome: 'Plataforma',
      danger: 'Baixo',
      status: 'current',
    },
    {
      id: 'freight-yard',
      name: 'Patio de Carga',
      biome: 'Industrial',
      danger: 'Medio',
      status: 'available',
    },
    {
      id: 'flooded-crossing',
      name: 'Travessia Inundada',
      biome: 'Mare',
      danger: 'Medio',
      status: 'locked',
    },
    {
      id: 'kennel-edge',
      name: 'Borda do Canil',
      biome: 'Hostil',
      danger: 'Alto',
      status: 'locked',
    },
  ]
}
